apiVersion: v1
kind: Service
metadata:
  name: pingpong-ext-svc
  namespace: exercises-namespace
spec:
  type: LoadBalancer
  selector:
    app: pingpong
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
