apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: exercises-namespace
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBZgLZna3xqMZrz2gUM9xQ1K444+BVsIEYzC/azWlflQppw/Nk09Uef0LzUrrTfXZgr23fZsZ72OVVolCKN2+0451h8WsaxME2XAigGDtWE6DBQFFW91HU4nP0lKpiUHVBiESmZ8DRnQRqWJFhgeijhqiCSmZ2KwFWnEIn+Zqh8aPo8zvIh6NU618ja4abP/ejBXBYt5bG1d8dzEjh02fHSfGaG5IK2cXUn7Tri7KyVRBmCY3+BTsQ/2dh+ruAMyEtcqiNsqTBOQmKl5nm+sryu2bBqFG3ZD7++dvO5b5qQ8tXu7aTgi+r1Fxiq6mNeuvPg1+0xI1T/JvOR5hMOxzphUVJGYs1ldkv1QmkyAyYKNORT23TckpsNJ5CxxmxnxyWqnEXn6dz+EvMdsShEOLN0xH6lXyQi385qLTWZ8o+wG3nrgsMv6gkhcf/xrspC7FepGBbJcye4TAUOaYkI7j3tR1hDbeiLIrm+r+EbgkJP+YLgKbx5V5xhNojfV5eD+Pe3wbjlVxANrVd02Z4Br1Qhs6D5EdSTYCoOAKH3UsfeAs3Xoh7GGz1RdQ6UE+R9ipNPNS/qxcG2TiwmvuOCkC/fl4OjLbuilhppH/vNLr/BfdD5lartHXTNFcR3g3LxVz1LjCIgOQWxFDNqEwvv5g/DVqMXfKzZOLdBmmtbk6kh8eSDtggmqUmVdZgCYwGAz1qpQkDpZeW/z3uqbnM=
  template:
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: exercises-namespace

