apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mainapplication-ksvc
  namespace: exercises-namespace
spec:
  template:
    metadata:
      name: mainapplication-ksvc-v3
    spec:
      containers:
        - image: ptuomola/mainreader:0.7.0
          env:
            - name: MESSAGE
              valueFrom: 
                configMapKeyRef:
                  name: project-config
                  key: MESSAGE        
