apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"generation":3,"labels":{"kustomize.toolkit.fluxcd.io/checksum":"0011a6f8b1ac4b49fe476e78ab35f27e4fa445d1","kustomize.toolkit.fluxcd.io/name":"project-app","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"backend-dep","namespace":"project-namespace","resourceVersion":"8125","uid":"6341080d-7048-4aaf-97fc-6482d10f993a"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"backend"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"backend"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"postgres-password"}}],"image":"ptuomola/backend:e511b66d455ab2814b180616142a6bc7eee7454a","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8080,"scheme":"HTTP"},"initialDelaySeconds":90,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"backend","readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":8080,"scheme":"HTTP"},"initialDelaySeconds":60,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"cpu":"150m","memory":"160Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":2,"conditions":[{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"message":"ReplicaSet \"backend-dep-c8764d4d9\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":3,"readyReplicas":2,"replicas":2,"updatedReplicas":2}}
    generation: 4
    labels:
      kustomize.toolkit.fluxcd.io/checksum: 0011a6f8b1ac4b49fe476e78ab35f27e4fa445d1
      kustomize.toolkit.fluxcd.io/name: project-app
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: backend-dep
    namespace: project-namespace
    resourceVersion: "11359"
    uid: 6341080d-7048-4aaf-97fc-6482d10f993a
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: backend
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          config.linkerd.io/skip-outbound-ports: "4222"
          linkerd.io/inject: enabled
        labels:
          app: backend
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: postgres-password
          image: ptuomola/backend:e511b66d455ab2814b180616142a6bc7eee7454a
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 90
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: backend
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 150m
              memory: 160Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - message: ReplicaSet "backend-dep-55f5d7fcd6" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 4
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "4"
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"generation":3,"labels":{"kustomize.toolkit.fluxcd.io/checksum":"0011a6f8b1ac4b49fe476e78ab35f27e4fa445d1","kustomize.toolkit.fluxcd.io/name":"project-app","kustomize.toolkit.fluxcd.io/namespace":"flux-system"},"name":"broadcaster-dep","namespace":"project-namespace","resourceVersion":"8315","uid":"e43a6485-2546-499d-8984-cd81a8c8239e"},"spec":{"progressDeadlineSeconds":600,"replicas":6,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"broadcaster"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"linkerd.io/inject":"enabled"},"labels":{"app":"broadcaster"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"broadcaster-apikey"}}],"image":"ptuomola/broadcaster:e511b66d455ab2814b180616142a6bc7eee7454a","imagePullPolicy":"Always","name":"broadcaster","terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":6,"conditions":[{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"message":"ReplicaSet \"broadcaster-dep-55cf548b45\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":3,"readyReplicas":6,"replicas":6,"updatedReplicas":6}}
    generation: 4
    labels:
      kustomize.toolkit.fluxcd.io/checksum: 0011a6f8b1ac4b49fe476e78ab35f27e4fa445d1
      kustomize.toolkit.fluxcd.io/name: project-app
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: broadcaster-dep
    namespace: project-namespace
    resourceVersion: "11518"
    uid: e43a6485-2546-499d-8984-cd81a8c8239e
  spec:
    progressDeadlineSeconds: 600
    replicas: 6
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: broadcaster
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          config.linkerd.io/skip-outbound-ports: "4222"
          linkerd.io/inject: enabled
        labels:
          app: broadcaster
      spec:
        containers:
        - envFrom:
          - secretRef:
              name: broadcaster-apikey
          image: ptuomola/broadcaster:e511b66d455ab2814b180616142a6bc7eee7454a
          imagePullPolicy: Always
          name: broadcaster
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    conditions:
    - message: Deployment does not have minimum availability.
      reason: MinimumReplicasUnavailable
      status: "False"
      type: Available
    - message: ReplicaSet "broadcaster-dep-7c7fc98b4" is progressing.
      reason: ReplicaSetUpdated
      status: "True"
      type: Progressing
    observedGeneration: 4
    replicas: 6
    unavailableReplicas: 6
    updatedReplicas: 6
kind: List
metadata: {}
---
