apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/backend-deployment.yaml
- manifests/backend-service.yaml
- manifests/persistentvolumeclaim.yaml
- manifests/postgres-service.yaml
- manifests/ingress.yaml
- manifests/postgres-deployment.yaml
- manifests/project-deployment.yaml
- manifests/project-service.yaml

images:
- name: PROJECT/IMAGE
  newName: ptuomola/project:0.5.0
- name: BACKEND/IMAGE
  newName: ptuomola/backend:0.3.0
