apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingpong-ingress
  annotations: 
    traefik.ingress.kubernetes.io/rule-type: PathStrip
spec:
  rules:
  - http:
      paths:
      - path: /pingpong
        backend:
          serviceName: pingpong-svc
          servicePort: 2347
      - path: /
        backend:
          serviceName: project-svc
          servicePort: 2347
