apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/backend-service.yaml
- manifests/postgres-service.yaml
- manifests/ingress.yaml
- manifests/postgres-deployment.yaml
- manifests/backend-deployment.yaml
- manifests/project-deployment.yaml
- manifests/project-service.yaml
- manifests/postgres-sealedsecret.yaml
- manifests/broadcaster-sealedsecret.yaml
- manifests/broadcaster-deployment.yaml
namespace: project-namespace
images:
- name: BACKEND/IMAGE
  newName: ptuomola/backend
  newTag: e511b66d455ab2814b180616142a6bc7eee7454a
- name: BROADCASTER/IMAGE
  newName: ptuomola/broadcaster
  newTag: e511b66d455ab2814b180616142a6bc7eee7454a
- name: PROJECT/IMAGE
  newName: ptuomola/project
  newTag: e511b66d455ab2814b180616142a6bc7eee7454a
