apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/backend-service.yaml
- manifests/postgres-service.yaml
- manifests/ingress.yaml
- manifests/postgres-deployment.yaml
- manifests/backend-deployment.yaml
- manifests/project-deployment.yaml
- manifests/project-service.yaml
- manifests/postgres-sealedsecret.yaml
- manifests/broadcaster-sealedsecret.yaml
- manifests/broadcaster-deployment.yaml
namespace: project-namespace
images:
- name: BACKEND/IMAGE
  newName: ptuomola/backend
  newTag: 041617e42302740f66b4870dfc2c33ebea7e7f68
- name: BROADCASTER/IMAGE
  newName: ptuomola/broadcaster
  newTag: 041617e42302740f66b4870dfc2c33ebea7e7f68
- name: PROJECT/IMAGE
  newName: ptuomola/project
  newTag: 041617e42302740f66b4870dfc2c33ebea7e7f68
