apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/backend-service.yaml
- manifests/postgres-service.yaml
- manifests/ingress.yaml
- manifests/postgres-deployment.yaml
- manifests/backend-deployment.yaml
- manifests/project-deployment.yaml
- manifests/project-service.yaml
- manifests/postgres-sealedsecret.yaml
- manifests/broadcaster-sealedsecret.yaml
- manifests/broadcaster-deployment.yaml
namespace: project-namespace
images:
- name: PROJECT/IMAGE
  newName: ptuomola/project:0.7.0
- name: BACKEND/IMAGE
  newName: ptuomola/backend:0.6.0
- name: BROADCASTER/IMAGE
  newName: ptuomola/broadcaster:0.1.0
