apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/namespace.yaml
- manifests/backend-service.yaml
- manifests/postgres-service.yaml
- manifests/ingress.yaml
- manifests/postgres-deployment.yaml
- manifests/backend-deployment.yaml
- manifests/project-deployment.yaml
- manifests/project-service.yaml
- manifests/postgres-sealedsecret.yaml
- manifests/broadcaster-sealedsecret.yaml
- manifests/broadcaster-deployment.yaml
namespace: project-namespace
images:
- name: BACKEND/IMAGE
  newName: ptuomola/backend
  newTag: d2c64f0b55c69ca308df1d36118450bbd240fe1e
- name: BROADCASTER/IMAGE
  newName: ptuomola/broadcaster
  newTag: d2c64f0b55c69ca308df1d36118450bbd240fe1e
- name: PROJECT/IMAGE
  newName: ptuomola/project
  newTag: d2c64f0b55c69ca308df1d36118450bbd240fe1e
