apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-usage
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: BACKEND/IMAGE
          env: 
          - name: POSTGRES_PASSWORD
            value: POSTGRES_PASSWORD_VALUE
          resources:
            limits:
              cpu: "150m"
              memory: "160Mi"
          readinessProbe:
            initialDelaySeconds: 30 # Initial delay until the readiness is tested
            periodSeconds: 10 # How often to test
            httpGet:
               path: /healthz
               port: 8080
          livenessProbe:
            initialDelaySeconds: 60 # Initial delay until the liveness is tested
            periodSeconds: 10 # How often to test
            httpGet:
               path: /healthz
               port: 8080
