apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapplication-dep
  namespace: exercises-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapplication 
  template:
    metadata:
      labels:
        app: mainapplication
    spec:
      containers:
        - name: mainapplication
          image: ptuomola/mainreader:0.4.0
          imagePullPolicy: Always
          env:
            - name: MESSAGE
              valueFrom: 
                configMapKeyRef:
                  name: project-config
                  key: MESSAGE
          resources:
             limits:
                cpu: 200m
                memory: 150Mi

