apiVersion: v1
kind: Service
metadata:
  name: project-svc
  namespace: project-namespace
spec:
  type: ClusterIP
  selector:
    app: project 
  ports:
    - port: 2347
      protocol: TCP
      targetPort: 8080
