apiVersion: batch/v1
kind: CronJob
metadata:
  name: posttodo
  namespace: project-namespace
spec:
  schedule: "0 0 * * *" 
  jobTemplate:
    spec:
      template:
        spec: 
          containers:
          - name: posttodo
            image: ptuomola/posttodo
            imagePullPolicy: Always
          restartPolicy: Never # This time we'll run it only once
