{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "broadcaster-apikey",
    "namespace": "project-namespace",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "broadcaster-apikey",
        "namespace": "project-namespace",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "BROADCASTER_APIKEY": "AgBf4cbieaJMqwzlCvhxLcpIErMgsYBZLnQTcIARbVKVbC0C7tcOJUGNXP9clCIJ9x9SXmyPWKrAKaEfDAz/L3Z2K0uSEI5ucN4d31d6Omi5z2cmLyJlCYHVam1IDMqOeHM2iaNwKf6YS418NAz2Zf4PIauuP4RtIRBQqMyiaanrLr7VZMtASZzO0D61z71jg5IqHvK43DddyED4o2TzujtX+83QZNDW0OHLmAA9HVftVjLWzxrYUGPeZisKzbvSE9Kqw6ONWRfgbwIaqxZQmrwxpin6Ip8JUWf5T2fd3ub12ej7SUqv7PF8NW3uIgy5gzXoLURvPTAo79RjAkiLwikKVGgoDG9FA0foyjvVXNoI80bZQeRlq0zOND17hzvqFhXHF+p13UjzkpDjuHPl+lmlVJ+30e+mHst2kKf1Xs1WRnmDKOw0K1/SHdfmYmRg0HyYvo8kxpCPBZJAJuB5t7IfXXi6Gvi0CffjZVMkNgmxOevjviIJLNyK4VBs9S7QMXmEnYoTxJzHa3GNUnR3qfUt2egWsgXPGV5CYoDnEDHVoECqphvfyEaU+/DX1TQXEtyeXSJoFmUfaZ1HqRJwcG5dqX+85Kd6usMxSmuQ1evG4gCA1vIDZCVpmdNWXxXqoY2H6aLBLG6wb8vEiRV8i4xt+qRerUe6wqH72heh2VgdCOtVKYl2Ofj6pJkawmlZevSbpp6jVrLCyzVFERfELiRB+lgMEdTgzHzBcyIDG98okAa5AuLWb3X0JqZ6fPF8"
    }
  }
}
