{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "broadcaster-apikey",
    "namespace": "project-namespace",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "broadcaster-apikey",
        "namespace": "project-namespace",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "BROADCASTER_APIKEY": "AgBJXJX3vvVxxBINgZGKhNWO9qN+O8haxAk56BgzrY5XECLhfF3lrxxYTxT7tFBftcf+AVZDD4Y/ooOmOM919E7tJEddqRlcH0Ibia2OsUAKyedtNET7aW+D9Huzr5UQJXkk421csPAJ43RowTOS5SeT0cF++tIuGVk7XVevhEeSWNmmZGk6puSTuXn/9RAY2/acw3Kp6lEfg0DEBs9G3fqhzAtOoM0Bz2S2f72vAHoYUyTe8v45g1rUi19FMyb6i2OQs6gTtfdff249EvB3z+7OE7wBZ1oQ/joVt7flPWvs091SwyACJDiY8btv9MHnX8cMVcWqkcFled4b1aR51KceoXlliJrncrTCpr/WBnGjPGQ6Bk3QTI2IpipjaWQpjTtE35zCdnQvTKNvloutEyMsFXA7lZaA5GU46Qa4DvuHb7knT2Rtl/Flv5Ebh68Y4X+dvgbfPzgJ5LIGk1XC1CXqJ22VC2tZ4J4QWP8vduKMWV1bhPgVgA1uw43HPG1Fr9z+ItoD2GXczwxNNIrh7noz7+TV6Ora4gCdJNL2qf6aUZE/JUtqy0avbSIgp+j59g/FzAtpWXhgeXPNcoFRI8bWJsCj+qQBelW0FUNpywjZAZQOAtOlxNx7iXNEmhQ1RL0v2dn5fyGNO9jXoGw0Kxzp4SbRiIIwx2039w4OFTH/j5vErz2xQc52iIbDzQVmHa60+BIpzE8IhHhTOZl4wt+3tOtXv1scBf7tnbw9CaeBSMqvUVGEk3ZgfMg4O/AP"
    }
  }
}
