{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-password",
    "namespace": "project-namespace",
    "creationTimestamp": null,
    "annotations": {
      "sealedsecrets.bitnami.com/cluster-wide": "true"
    }
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-password",
        "namespace": "project-namespace",
        "creationTimestamp": null,
        "annotations": {
          "sealedsecrets.bitnami.com/cluster-wide": "true"
        }
      }
    },
    "encryptedData": {
      "POSTGRES_PASSWORD": "AgA9NlV996XeIDCQxwvqoX9VqZA0bns0wmU/5NvH2dRGt2qVQUeOy68G/232aIe6beffqrE28ekvHf/1AG6SP8PrsARWcPQdq+kuImmVl/Asg/TygGOdnJc09i8LFkv1C3vemcJSaS0QN2z3DODUd8MsaoOZcQBtONpwLS/F48cza9R4PBmgnzeXEahGBNFylcGWPk1Yw0+97H7sqEgEYCUdZd/Pxn0FNQStRtXVR8CiC7aFbjPpJ6Vc2CmkwedYNBAODvijyetbhsM6pGh3Hx03wXPEKdTXdUzHP6u/ioupbkOL2AcuXx2v8X+AgHuJ2EdfZoPGkk1g6rmU21JLef/0o7tFh9drkxSuHyBj1rB2ahHeiacTE0Wcn0Sd0xoh4DPpe2izh76+lcB3yq6nqVL29/uIZ8MZgwOR7Js/WwRUXdzcFA//kO6P1gKHlftjB7HrF68qPSv8G0PiCnWTDSexrSQCcTTSgVcWjAaB+bHMJu6ZHUGtTxHg7EKuy60ET+Lpn4ducwBmhwzzjxpzmpevwJzauc8z4gc+EerZQTsE2Z4llsM1nzbpPo5NqNM0D/MURvus1Ajr+48vRE/lcQPlFRWWrJ2iLVo6GSZ04ICGInfljoN4x6aoSaFBvg/Vg/fXVkpe1nwfrQyPPo0Fz9hJ+3+4KgcY29+oZvMfinqb9lhpuYWCFx2aC2F4q2O7jMrM7QKK9kvCU3/py94="
    }
  }
}
