name: Exercise 4.08

on:
  push:
    paths:
      - 'part4/ex4.08/**'
      - '.github/workflows/ex408.yaml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build project
      working-directory: ./part4/ex4.08/project
      run: mvn package -Drepository=docker.io/ptuomola/project -Dtag=${{ github.sha }} 

    - name: Push project
      working-directory: ./part4/ex4.08/project
      run: docker push ptuomola/project:${{github.sha}}

    - name: Build backend
      working-directory: ./part4/ex4.08/backend
      run: mvn -X package -Drepository=docker.io/ptuomola/backend -Dtag=${{ github.sha }}

    - name: Push backend
      working-directory: ./part4/ex4.08/backend
      run: docker push ptuomola/backend:${{github.sha}}

    - name: Build broadcaster
      working-directory: ./part4/ex4.08/broadcaster
      run: mvn package -Drepository=docker.io/ptuomola/broadcaster -Dtag=${{ github.sha }}

    - name: Push broadcaster
      working-directory: ./part4/ex4.08/broadcaster
      run: docker push ptuomola/broadcaster:${{github.sha}}

  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2

    - name: Set up Kustomize
      working-directory: ./part4/ex4.08/
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Update yamls
      working-directory: ./part4/ex4.08/
      run: |-
        ./kustomize edit set image PROJECT/IMAGE=ptuomola/project:${{github.sha}} BACKEND/IMAGE=ptuomola/backend:${{github.sha}} BROADCASTER/IMAGE=ptuomola/broadcaster:${{github.sha}}

    # Commit and push
    - uses: EndBug/add-and-commit@v5
      with:
        add: './part4/ex4.08/kustomization.yaml'
        message: New version release for gitops-app ${{ github.sha }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

