apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-pingpong
          persistentVolumeClaim:
            claimName: pingpong-claim
      containers:
        - name: pingpong
          image: ptuomola/pingpong:0.2.0
          imagePullPolicy: Always
          volumeMounts:
          - name: shared-pingpong
            mountPath: /usr/src/app/files
            
